### ISSUE TITLE
Vybrat obrázek pro rozložení speciálních znaků na české klávesnici

### ISSUE THREAD

**Issue by hason** [webuni/czechitas-php-start#1]
1.
![](http://www.ceskaklavesnice.cz/images/klvs_cz_alt.jpg)

2.
![](http://dusan.pc-slany.cz/klavesnice/obrazky/pravy-alt.gif)

3.
![](http://www.mojeskola.eu/wp-content/uploads/2013/09/klavesove_zkratky.jpg)

**Comment by prodejledu** [comment]
2

**Comment by Jakub-Fajkus** [comment]
3, ale tezko rict, jestli to nebude vytistene vypadat divne

**Comment by hason** [comment]
U 2 a 3 se mi nezdá, že by na těch číslech vše fungovala. Mě na linuxu funguje, až na pár znaků, to co je na obrázku 1. Takže za mě 1.

**Comment by Rockuo** [comment]
1

**Comment by hason** [comment]
Vytisknuta 1, snad to bude vidět.
